sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrudragan/docker-react -f DockerFile.dev .

script:
  # run tests with immediate exit!
  - docker run alexandrudragan/docker-react npm run test -- --coverage